apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: control-plane-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  virtualRouters:
    - localASN: 65131
      exportPodCIDR: true
      neighbors:
        - peerAddress: "172.18.0.6/16"
          peerASN: 65130
