apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-addons
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/mikejoh/argocd-poc.git
      revision: HEAD
      directories:
      - path: k8s-addons/*
  template:
    metadata:
      name: '{{path[0]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/mikejoh/argocd-poc.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: kind-downstream-cluster
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

