apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s-addons
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mikejoh/k8s-apps.git
        revision: main
        directories:
          - path: charts/*
  template:
    metadata:
      name: "{{ path[0] }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/mikejoh/k8s-apps.git
        targetRevision: "{{ revision }}"
        path: "{{path}}"
      destination:
        name: kind-downstream-cluster
        namespace: "{{ path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
